# Тестирование модели на простом датасете из 100 строк

In [17]:
import pandas as pd
import re
from masker import mask_pii, mask_pii_with_mapping

In [18]:
from unmask import unmask_pii

In [19]:
df_simple_100= pd.read_csv('data/simple_data_100.csv')

In [20]:
df_simple_100.sample(10)

,original,masked
52,"Мой номер 79265554433, как подключить смс-банк?","Мой номер [PHONE], как подключить смс-банк?"
6,"Я Иванова Мария Петровна, мне нужна справка об...","Я [NAME], мне нужна справка об остатке по ипотеке"
18,"Подскажите, есть ли комиссия при снятии наличн...","Подскажите, есть ли комиссия при снятии наличн..."
79,Как закрыть кредитную карту 4276 1111 2222 3333?,Как закрыть кредитную карту [CARD]?
88,"Карта 4276 1111 2222 3333, как увеличить креди...","Карта [CARD], как увеличить кредитный лимит?"
32,"Я живу в Новосибирске, на улице Советской, д. ...","Я живу в [ADDRESS], как мне получить карту кур..."
76,"Я Соколова Елена, паспорт 4612 345678, забыла ...","Я [NAME], паспорт [PASSPORT], забыла номер дог..."
90,"Я Тимофеев Артем, мой телефон 89159887766, код...","Я [NAME], мой телефон [PHONE], код доступа не ..."
45,"Подскажите, работает ли отделение в субботу?","Подскажите, работает ли отделение в субботу?"
39,Я потерял кошелек с картой 4276 1234 5678 9012...,"Я потерял кошелек с картой [CARD], имя на карт..."

In [26]:
df_simple_100['pred'] = None
df_simple_100['mapping'] = None

for idx, row in df_simple_100.iterrows():
    res = mask_pii_with_mapping(row['original'])
    df_simple_100.at[idx, 'pred'] = res.masked_text
    df_simple_100.at[idx, 'mapping'] = res.mapping

In [27]:
df_simple_100[['original', 'pred', 'mapping']].sample(10)

,original,pred,mapping
56,"Подскажите, как перевести деньги с карты на ка...","Подскажите, как перевести деньги с карты на ка...",{}
71,"Я Крылова Анна Ивановна, проживаю в Нижнем Нов...","Я Крылова Анна Ивановна, проживаю в [ADDRESS_1...",{'[ADDRESS_1]': 'Нижнем Новгороде'}
92,"Мой паспорт 4615 987123, хочу открыть ИИС","Мой паспорт [PASSPORT_1], хочу открыть ИИС",{'[PASSPORT_1]': '4615 987123'}
66,"Добрый вечер, я Николаев Сергей, мой номер 891...","Добрый вечер, я [NAME_1], мой номер [PHONE_1],...","{'[PHONE_1]': '89163334455', '[NAME_1]': 'Нико..."
44,"Я Смирнов Павел, паспорт 4617 123456, хочу офо...","Я [NAME_1], паспорт [PASSPORT_1], хочу оформит...","{'[PASSPORT_1]': '4617 123456', '[NAME_1]': 'С..."
35,"Здравствуйте, хочу подключить автоплатеж за ЖК...","Здравствуйте, хочу подключить автоплатеж за ЖК...",{'[CARD_1]': '2200 1111 2222 3333'}
74,"Здравствуйте, я хочу проверить, дошла ли зарплата","Здравствуйте, я хочу проверить, дошла ли зарплата",{}
28,"Я Артемьев Денис, мой телефон 89153456789, не ...","Я [NAME_1], мой телефон [PHONE_1], не могу вой...","{'[PHONE_1]': '89153456789', '[NAME_1]': 'Арте..."
57,"Я Морозов Игорь, проживаю в Красноярске, ул. М...","Я [NAME_1], проживаю в [ADDRESS_1], ул. Мира, ...","{'[ADDRESS_1]': 'Красноярске', '[NAME_1]': 'Мо..."
90,"Я Тимофеев Артем, мой телефон 89159887766, код...","Я [NAME_1], мой телефон [PHONE_1], код доступа...","{'[PHONE_1]': '89159887766', '[NAME_1]': 'Тимо..."

In [28]:
df_simple_100['unmask'] = df_simple_100.apply(lambda r: unmask_pii(r['pred'], r['mapping']),axis=1)

In [29]:
df_simple_100[['original', 'pred', 'unmask']].sample(10)

,original,pred,unmask
101,"Карта 4276 1111 2222 3333, ошибочно перевел 50...","Карта [CARD_1], ошибочно перевел 5000 рублей н...","Карта 4276 1111 2222 3333, ошибочно перевел 50..."
49,"Карта 4276 1111 2222 3333 заблокирована, что д...","Карта [CARD_1] заблокирована, что делать?","Карта 4276 1111 2222 3333 заблокирована, что д..."
40,"Мой адрес регистрации изменился, теперь я в Ро...","Мой адрес регистрации изменился, теперь я в [A...","Мой адрес регистрации изменился, теперь я в Ро..."
67,Измените лимит на снятие наличных по карте 427...,Измените лимит на снятие наличных по карте [CA...,Измените лимит на снятие наличных по карте 427...
82,"Подскажите, можно ли оплатить кредит картой др...","Подскажите, можно ли оплатить кредит картой др...","Подскажите, можно ли оплатить кредит картой др..."
71,"Я Крылова Анна Ивановна, проживаю в Нижнем Нов...","Я Крылова Анна Ивановна, проживаю в [ADDRESS_1...","Я Крылова Анна Ивановна, проживаю в Нижнем Нов..."
44,"Я Смирнов Павел, паспорт 4617 123456, хочу офо...","Я [NAME_1], паспорт [PASSPORT_1], хочу оформит...","Я Смирнов Павел, паспорт 4617 123456, хочу офо..."
90,"Я Тимофеев Артем, мой телефон 89159887766, код...","Я [NAME_1], мой телефон [PHONE_1], код доступа...","Я Тимофеев Артем, мой телефон 89159887766, код..."
83,"Здравствуйте, я потерял телефон, номер 7916555...","Здравствуйте, я потерял телефон, номер [PHONE_...","Здравствуйте, я потерял телефон, номер 7916555..."
64,Как заблокировать карту 2200 1111 2222 3333 че...,Как заблокировать карту [CARD_1] через смс?,Как заблокировать карту 2200 1111 2222 3333 че...

In [30]:
df_simple_100[df_simple_100.original!=df_simple_100.unmask]

Empty DataFrame
Columns: [original, masked, pred, mapping, unmask]
Index: []