In [1]:
import pandas as pd
import re
from masker import mask_pii

In [2]:
from metrics import confusion_matrix, metrics

In [3]:
df = pd.read_csv('data/simple_data.csv')

In [4]:
matrix = confusion_matrix(df.masked, df.masked)

In [5]:
matrix

       entity  TP  FP  FN
0   [ADDRESS]   2   0   0
1      [CARD]   2   0   0
2     [EMAIL]   4   0   0
3      [NAME]   7   0   0
4  [PASSPORT]   3   0   0
5     [PHONE]   3   0   0
6   __TOTAL__  21   0   0

In [6]:
metrics(df.masked, df.masked)

       entity  Precision  Recall   F1
0   [ADDRESS]        1.0     1.0  1.0
1      [CARD]        1.0     1.0  1.0
2     [EMAIL]        1.0     1.0  1.0
3      [NAME]        1.0     1.0  1.0
4  [PASSPORT]        1.0     1.0  1.0
5     [PHONE]        1.0     1.0  1.0
6   __TOTAL__        1.0     1.0  1.0

In [7]:
df_res = pd.read_csv('data/analysis_results.csv')

In [8]:
df_res

,id,text,target,pred,is_match,mapping
0,2,Здравствуйте меня зовут Иван Иванов хочу узнат...,Здравствуйте меня зовут [NAME] хочу узнать поч...,Здравствуйте меня зовут [NAME] хочу узнать поч...,1,{'[NAME_1]': 'Иван Иванов'}
1,3,Добрый день это Петр Петров я не могу войти в ...,Добрый день это [NAME] я не могу войти в мобил...,Добрый день это [NAME] я не могу войти в мобил...,1,{'[NAME_1]': 'Петр Петров'}
2,4,Меня зовут Сергей Сидоров у меня возникла проб...,Меня зовут [NAME] у меня возникла проблема с п...,Меня зовут [NAME] у меня возникла проблема с п...,1,{'[NAME_1]': 'Сергей Сидоров'}
3,5,Здравствуйте меня зовут Анна Кузнецова я хочу ...,Здравствуйте меня зовут [NAME] я хочу изменить...,Здравствуйте меня зовут [NAME] я хочу изменить...,1,{'[NAME_1]': 'Анна Кузнецова'}
4,6,Я клиент банка Иван Иванов и у меня не проходи...,Я клиент банка [NAME] и у меня не проходит пла...,Я клиент банка [NAME] и у меня не проходит пла...,1,{'[NAME_1]': 'Иван Иванов'}
...,...,...,...,...,...,...
61,63,Помогите разобраться с доступом использовал да...,Помогите разобраться с доступом использовал да...,Помогите разобраться с доступом использовал да...,1,{'[CARD_1]': '5536 9100 1122 3344'}
62,64,При попытке входа система просит подтвердить д...,При попытке входа система просит подтвердить д...,При попытке входа система просит подтвердить д...,1,{'[PHONE_1]': '89167778899'}
63,65,Не получается восстановить доступ указывал так...,Не получается восстановить доступ указывал так...,Не получается восстановить доступ указывал так...,1,{'[EMAIL_1]': 'helpclient@mail.ru'}
64,66,Пытаюсь войти в систему данные которые вводил ...,Пытаюсь войти в систему данные которые вводил ...,Пытаюсь войти в систему данные которые вводил ...,1,"{'[NAME_1]': 'Иван Иванов', '[PHONE_1]': '8916..."
65,67,Не получается выполнить вход пробовал использо...,Не получается выполнить вход пробовал использо...,Не получается выполнить вход пробовал использо...,1,{'[CARD_1]': '4276 9999 8888 7777'}

In [9]:
metrics(df_res.target, df_res.pred)

       entity  Precision    Recall        F1
0   [ADDRESS]        1.0  0.750000  0.857143
1      [CARD]        1.0  1.000000  1.000000
2     [EMAIL]        1.0  1.000000  1.000000
3      [NAME]        1.0  0.829268  0.906667
4  [PASSPORT]        1.0  1.000000  1.000000
5     [PHONE]        1.0  1.000000  1.000000
6   __TOTAL__        1.0  0.915888  0.956098

In [10]:
df_res['pred_2'] = df_res.target.apply(lambda x: mask_pii(x))

In [11]:
metrics(df_res.target, df_res.pred_2)

       entity  Precision  Recall   F1
0   [ADDRESS]        1.0     1.0  1.0
1      [CARD]        1.0     1.0  1.0
2     [EMAIL]        1.0     1.0  1.0
3      [NAME]        1.0     1.0  1.0
4  [PASSPORT]        1.0     1.0  1.0
5     [PHONE]        1.0     1.0  1.0
6   __TOTAL__        1.0     1.0  1.0

In [12]:
df['pred'] = df.original.apply(lambda x: mask_pii(x))

In [13]:
df

,original,masked,pred
0,"Здравствуйте, меня зовут Екатерина Смирнова, я...","Здравствуйте, меня зовут [NAME], я потеряла ка...","Здравствуйте, меня зовут [NAME], я потеряла ка..."
1,"Добрый день! Мой номер телефона 89161234567, н...","Добрый день! Мой номер телефона [PHONE], не пр...","Добрый день! Мой номер телефона [PHONE], не пр..."
2,"Хочу сменить тариф, подскажите, какие есть вар...","Хочу сменить тариф, подскажите, какие есть вар...","Хочу сменить тариф, подскажите, какие есть вар..."
3,"Здравствуйте, напоминаю: моя почта ivanpetrov@...","Здравствуйте, напоминаю: моя почта [EMAIL], жд...","Здравствуйте, напоминаю: моя почта [EMAIL], жд..."
4,Нужно сменить адрес регистрации: был прописан ...,Нужно сменить адрес регистрации: был прописан ...,Нужно сменить адрес регистрации: был прописан ...
5,"Я Иванов Сергей Петрович, 15 марта 1985 г.р., ...","Я [NAME], паспорт [PASSPORT], не могу войти в ...","Я [NAME], 15 марта 1985 г.р., паспорт [PASSPOR..."
6,"Подскажите, работает ли отделение на Ленинград...","Подскажите, работает ли отделение на Ленинград...","Подскажите, работает ли отделение на [ADDRESS]..."
7,"Карта 4276 1234 5678 9012, спишите деньги за к...","Карта [CARD], спишите деньги за кредит сегодня","Карта [CARD], спишите деньги за кредит сегодня"
8,"Здравствуйте, я Артем, забыл пин-код, можно во...","Здравствуйте, я [NAME], забыл пин-код, можно в...","Здравствуйте, я [NAME], забыл пин-код, можно в..."
9,"Измените, пожалуйста, номер телефона для смс-о...","Измените, пожалуйста, номер телефона для смс-о...","Измените, пожалуйста, номер телефона для смс-о..."
10,"Мой email: a.kuznetsova@inbox.ru, продублируйт...","Мой email: [EMAIL], продублируйте договор на э...","Мой email: [EMAIL], продублируйте договор на э..."
11,"Здравствуйте! Я хочу открыть вклад, но я в ком...","Здравствуйте! Я хочу открыть вклад, но я в ком...","Здравствуйте! Я хочу открыть вклад, но я в ком..."
12,"Добрый день, это Петровна из 56 квартиры, дом ...","Добрый день, это [NAME] из [ADDRESS], мне пенс...","Добрый день, это [NAME] из 56 квартиры, дом 10..."
13,"Потерял телефон с симкой, номер привязан к кар...","Потерял телефон с симкой, номер привязан к кар...","Потерял телефон с симкой, номер привязан к кар..."
14,"Нужна справка 2-НДФЛ за 2023 год, паспорт 4508...","Нужна справка 2-НДФЛ за 2023 год, паспорт [PAS...","Нужна справка 2-НДФЛ за 2023 год, паспорт [PAS..."
15,"Здравствуйте, меня зовут Мария, я перевела ден...","Здравствуйте, меня зовут [NAME], я перевела де...","Здравствуйте, меня зовут [NAME], я перевела де..."
16,Какой курс обмена валюты сегодня в отделении н...,Какой курс обмена валюты сегодня в отделении н...,Какой курс обмена валюты сегодня в отделении н...
17,"Сменил прописку, теперь адрес: Омск, ул. Красн...","Сменил прописку, теперь адрес: [ADDRESS]. Обно...","Сменил прописку, теперь адрес: [ADDRESS], ул. ..."
18,"Я Сидоров Максим Алексеевич, паспорт 4617 5544...","Я [NAME], паспорт [PASSPORT], прошу выдать кар...","Я [NAME], паспорт [PASSPORT], прошу выдать кар..."
19,У меня в кредитном договоре ошибка: вместо s.m...,У меня в кредитном договоре ошибка: вместо [EM...,У меня в кредитном договоре ошибка: вместо [EM...

In [14]:
df.original

0     Здравствуйте, меня зовут Екатерина Смирнова, я...
1     Добрый день! Мой номер телефона 89161234567, н...
2     Хочу сменить тариф, подскажите, какие есть вар...
3     Здравствуйте, напоминаю: моя почта ivanpetrov@...
4     Нужно сменить адрес регистрации: был прописан ...
5     Я Иванов Сергей Петрович, 15 марта 1985 г.р., ...
6     Подскажите, работает ли отделение на Ленинград...
7     Карта 4276 1234 5678 9012, спишите деньги за к...
8     Здравствуйте, я Артем, забыл пин-код, можно во...
9     Измените, пожалуйста, номер телефона для смс-о...
10    Мой email: a.kuznetsova@inbox.ru, продублируйт...
11    Здравствуйте! Я хочу открыть вклад, но я в ком...
12    Добрый день, это Петровна из 56 квартиры, дом ...
13    Потерял телефон с симкой, номер привязан к кар...
14    Нужна справка 2-НДФЛ за 2023 год, паспорт 4508...
15    Здравствуйте, меня зовут Мария, я перевела ден...
16    Какой курс обмена валюты сегодня в отделении н...
17    Сменил прописку, теперь адрес: Омск, ул. Красн...
18    Я Сидоров Максим Алексеевич, паспорт 4617 5544...
19    У меня в кредитном договоре ошибка: вместо s.m...
Name: original, dtype: str

In [15]:
df.pred

0     Здравствуйте, меня зовут [NAME], я потеряла ка...
1     Добрый день! Мой номер телефона [PHONE], не пр...
2     Хочу сменить тариф, подскажите, какие есть вар...
3     Здравствуйте, напоминаю: моя почта [EMAIL], жд...
4     Нужно сменить адрес регистрации: был прописан ...
5     Я [NAME], 15 марта 1985 г.р., паспорт [PASSPOR...
6     Подскажите, работает ли отделение на [ADDRESS]...
7        Карта [CARD], спишите деньги за кредит сегодня
8     Здравствуйте, я [NAME], забыл пин-код, можно в...
9     Измените, пожалуйста, номер телефона для смс-о...
10    Мой email: [EMAIL], продублируйте договор на э...
11    Здравствуйте! Я хочу открыть вклад, но я в ком...
12    Добрый день, это [NAME] из 56 квартиры, дом 10...
13    Потерял телефон с симкой, номер привязан к кар...
14    Нужна справка 2-НДФЛ за 2023 год, паспорт [PAS...
15    Здравствуйте, меня зовут [NAME], я перевела де...
16    Какой курс обмена валюты сегодня в отделении н...
17    Сменил прописку, теперь адрес: [ADDRESS], ул. ...
18    Я [NAME], паспорт [PASSPORT], прошу выдать кар...
19    У меня в кредитном договоре ошибка: вместо [EM...
Name: pred, dtype: str

In [16]:
metrics(df.masked, df.pred)

       entity  Precision  Recall        F1
0   [ADDRESS]   0.333333     1.0  0.500000
1      [CARD]   1.000000     1.0  1.000000
2     [EMAIL]   1.000000     1.0  1.000000
3      [NAME]   1.000000     1.0  1.000000
4  [PASSPORT]   1.000000     1.0  1.000000
5     [PHONE]   1.000000     1.0  1.000000
6   __TOTAL__   0.840000     1.0  0.913043